# Generated by Django 2.2.6 on 2019-10-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'study group',
                'verbose_name_plural': 'study groups',
                'db_table': 'users__studygroup',
            },
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=512, null=True, verbose_name='rank')),
                ('studygroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.StudyGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'study profile',
                'verbose_name_plural': 'study profiles',
                'db_table': 'users__studyprofile',
            },
        ),
    ]
