# Generated by Django 2.2.6 on 2019-10-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20191016_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise', verbose_name='упражнение'),
        ),
    ]
